### ISSUE TITLE
Error While Running Docker Standalone run_all.sh

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/gluu-docker#54] opened 2018-10-16 20:21 UTC
```
[I] Preparing cluster-wide configuration
[W] Configuration not found in Consul
[I] Creating new configuration, please input the following parameters
Enter Domain:                 example.gluu.org
Enter Country Code:           US
Enter State:                  TX
Enter City:                   Austin
Enter Email:                  example.user@sub.domain.gluu.org
Enter Organization:           VDM
Enter Admin/LDAP Password:    gluu1234!
Continue with the above settings? [Y/n]
[I] Deploying containers
[I] Generating configuration for the first time; this may take a moment
Unable to find image 'gluufederation/config-init:3.1.4_dev' locally
3.1.4_dev: Pulling from gluufederation/config-init
4fe2ade4980c: Already exists
6fc58a8d4ae4: Already exists
d3e6d7e9702a: Already exists
eb67688aeb85: Already exists
aab61efeccb1: Pull complete
260654189cfc: Pull complete
5e7a1cf6615d: Pull complete
ae9e0953b636: Pull complete
70dc7a95ec86: Pull complete
04501bdc547c: Pull complete
7dd6c2d11788: Pull complete
d71fe23c725a: Pull complete
9a3072d39a6c: Pull complete
Digest: sha256:134df964c23db6e16324b767c053c4952ecdada49a195e9633512858c30eff9a
Status: Downloaded newer image for gluufederation/config-init:3.1.4_dev
Config backend is ready.
Generating config.
  adding new key 'encoded_salt'
  adding new key 'orgName'
  adding new key 'country_code'
  adding new key 'state'
  adding new key 'city'
  adding new key 'hostname'
  adding new key 'admin_email'
  adding new key 'default_openid_jks_dn_name'
  adding new key 'pairwiseCalculationKey'
  adding new key 'pairwiseCalculationSalt'
  adding new key 'jetty_base'
  adding new key 'ldap_init_host'
  adding new key 'ldap_init_port'
  adding new key 'ldap_port'
  adding new key 'ldaps_port'
  adding new key 'ldap_truststore_pass'
  adding new key 'ldap_type'
  adding new key 'ldap_binddn'
  adding new key 'ldap_site_binddn'
  adding new key 'ldapTrustStoreFn'
Traceback (most recent call last):
  File "./scripts/entrypoint.py", line 965, in <module>
    cli()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "./scripts/entrypoint.py", line 859, in generate
    inum_appliance)
  File "./scripts/entrypoint.py", line 233, in generate_config
    cfg["city"],
  File "./scripts/entrypoint.py", line 728, in generate_ssl_certkey
    "-subj /C='{}'/ST='{}'/L='{}'/O='{}'/CN='{}'/emailAddress='{}'".format(country_code, state, city, org_name, domain, email),
UnicodeEncodeError: 'ascii' codec can't encode character u'\ufffd' in position 8: ordinal not in range(128)
```

The issue seems to be from the email address with too many `.`'s `example.user@sub.domain.gluu.org`

**Comment by iromli** [comment] 2018-10-16 20:33
Sorry, i was unable to reproduce the issue with same email as stated above. Are you sure there's no unicode character passed as user-inputs?

**Comment by afroDC** [comment] 2018-10-16 20:38
It's possible, it was using a french keyboard, I believe. Let me share the entry with you directly.

**Comment by iromli** [comment] 2019-02-04 20:36
Unable to reproduce this issue. Closing this one.

**Closed by iromli** 2019-02-04 20:36 UTC
Labels: bug
